{
 "title": "EGYM Fitness",
 "description": "Dashboard to display data collected via EGYM ",
 "tags": [ "egym" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": {
     "query": "label_values(egym_bio_age_total,user)"
    }
   },
   { "name": "maxAge", "query": "80" }
  ]
 },
 "panels": [
  { "title": "Age", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Years" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "egym_bio_age_total{user=\"$user\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "egym_bio_age_muscles{user=\"$user\"}",
     "legendFormat": "Muscles"
    },
    {
     "expr": "egym_bio_age_cardio{user=\"$user\"}",
     "legendFormat": "Cardio"
    },
    {
     "expr": "egym_bio_age_metabolic{user=\"$user\"}",
     "legendFormat": "Metabolic"
    },
    {
     "expr": "egym_bio_age_flexibility{user=\"$user\"}",
     "legendFormat": "Flexibility"
    }
   ]
  },
  { "title": "Muscles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Imbalances",
   "type": "gauge",
   "description": "Display (Im)balances for different muscle pairs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "egym_muscle_imbalance{user=\"$user\"}",
     "legendFormat": "{{antagonist_muscle}}__{{agonist_muscle}}"
    }
   ]
  },
  {
   "title": "Strengths",
   "type": "timeseries",
   "description": "Muscle strength measured by different exercises",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "egym_strength{user=\"$user\"}",
     "legendFormat": "{{muscle}}"
    }
   ]
  },
  {
   "title": "Mass",
   "type": "timeseries",
   "description": "Amount of muscle mass by different muscle (groups)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "expr": "egym_body{user=\"$user\", unit=\"KG\", type=~\"SEGMENTAL_MUSCLE_LEFT_ARM|SEGMENTAL_MUSCLE_LEFT_LEG|SEGMENTAL_MUSCLE_RIGHT_ARM|SEGMENTAL_MUSCLE_RIGHT_LEG|SEGMENTAL_MUSCLE_TRUNK|SKELETAL_MUSCLE_MASS\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Metabolic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Weight",
     "type": "timeseries",
     "description": "Weight compensation",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "targets": [
      {
       "expr": "egym_body{user=\"$user\", type=~\"WEIGHT|BODY_FAT_MASS|FAT_FREE_MASS\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Fat mass",
     "type": "timeseries",
     "description": "Fat mass composition",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "masskg" } },
     "targets": [
      {
       "expr": "egym_body{user=\"$user\", unit=\"KG\", type=~\"BODY_FAT_MASS|SEGMENTAL_FAT_LEFT_ARM|SEGMENTAL_FAT_LEFT_LEG|SEGMENTAL_FAT_RIGHT_ARM|SEGMENTAL_FAT_RIGHT_LEG|SEGMENTAL_FAT_TRUNK\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Water",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "litre" } },
     "targets": [
      {
       "expr": "egym_body{user=\"$user\", type=~\"EXTRA_CELLULAR_WATER|INTRA_CELLULAR_WATER|BODY_WATER\", unit=\"LITER\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Others",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "egym_body{user=\"$user\", type=~\"BODY_PHASE|VISCERAL_FAT_RATING\"}",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "egym_body{user=\"$user\", type=~\"BMI\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Flexibility",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flexibility",
     "type": "timeseries",
     "description": "Flexibility based on measured maximum rotation angles of different muscles",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "degree" } },
     "targets": [
      {
       "expr": "egym_flexibility{user=\"$user\", unit!=\"\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Trainings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "type": "status-history",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
     "targets": [
      {
       "parsingOptions": [
        {
         "dataPath": "fitness.workouts",
         "labelOptions": [],
         "timeFields": [
          { "timePath": "endDate" },
          { "timePath": "dateToGroup" }
         ]
        }
       ],
       "queryText": "query ($from: Date!, $to: Date!) {\n  fitness {\n    workouts(startDate: $from, endDate: $to) {\n      endDate\n      dateToGroup: endDate\n      exercises {\n        __typename\n      }\n    }\n\t}\n}\n"
      }
     ]
    }
   ]
  }
 ]
}